'use strict'

const CONTROL_PANEL_X = 10;
const CONTROL_PANEL_Y = 10;
const CONTROL_PANEL_WIDTH = 980;
const CONTROL_PANEL_HEIGHT = 30;

const VISUAL_PANEL_X = CONTROL_PANEL_X + CONTROL_PANEL_WIDTH + 10;
const VISUAL_PANEL_Y = CONTROL_PANEL_Y;
const VISUAL_PANEL_WIDTH = 190
const VISUAL_PANEL_HEIGHT = 780

const VISUAL_BPM_X = VISUAL_PANEL_X + 10;
const VISUAL_BPM_Y = VISUAL_PANEL_Y + 20;

const BPM_WIDGET_X = VISUAL_PANEL_X + 10;
const BPM_WIDGET_Y = VISUAL_BPM_Y + 10;
const BPM_WIDGET_WIDTH = VISUAL_PANEL_WIDTH - 20;
const BPM_WIDGET_HEIGHT = 30;

const OCTAVE_LABEL_X = VISUAL_PANEL_X + 10;
const OCTAVE_LABEL_Y = BPM_WIDGET_Y + BPM_WIDGET_HEIGHT + 20;

const OCTAVE_WIDGET_X = VISUAL_PANEL_X + 10;
const OCTAVE_WIDGET_Y = OCTAVE_LABEL_Y + 10;
const OCTAVE_WIDGET_WIDTH = VISUAL_PANEL_WIDTH - 20;
const OCTAVE_WIDGET_HEIGHT = 30;
const OCTAVE_WIDGET_SEGMENTS = 10;

const CHANNEL_LABEL_X = VISUAL_PANEL_X + 10;
const CHANNEL_LABEL_Y = OCTAVE_WIDGET_Y + OCTAVE_WIDGET_HEIGHT + 20;

const CHANNEL_WIDGET_X = VISUAL_PANEL_X + 10;
const CHANNEL_WIDGET_Y = CHANNEL_LABEL_Y + 10;
const CHANNEL_WIDGET_WIDTH = VISUAL_PANEL_WIDTH - 20;
const CHANNEL_WIDGET_HEIGHT = 30;
const CHANNEL_WIDGET_SEGMENTS = 16;

const WIDGET_DIVIDER_1_X = VISUAL_PANEL_X;
const WIDGET_DIVIDER_1_Y = CHANNEL_WIDGET_Y + CHANNEL_WIDGET_HEIGHT + 20;
const WIDGET_DIVIDER_1_WIDTH = VISUAL_PANEL_WIDTH;

const VALUE_WIDGET_X = VISUAL_PANEL_X + 20;
const VALUE_WIDGET_Y = WIDGET_DIVIDER_1_Y + 72;
const VALUE_WIDGET_HEIGHT = 100;
const VALUE_WIDGET_WIDTH = VISUAL_PANEL_WIDTH - 20;

const WIDGET_DIVIDER_2_X = VISUAL_PANEL_X;
const WIDGET_DIVIDER_2_Y = WIDGET_DIVIDER_1_Y + VALUE_WIDGET_HEIGHT;
const WIDGET_DIVIDER_2_WIDTH = VISUAL_PANEL_WIDTH;

const MIDI_OUTPUT_X = CONTROL_PANEL_X + 10;
const MIDI_OUTPUT_Y = CONTROL_PANEL_Y + 20;

const MAIN_PANEL_X = CONTROL_PANEL_X;
const MAIN_PANEL_Y = CONTROL_PANEL_Y + CONTROL_PANEL_HEIGHT + 10;
const MAIN_PANEL_WIDTH = CONTROL_PANEL_WIDTH;
const MAIN_PANEL_HEIGHT = 400;

const INGREDIENTS_PANEL_X = MAIN_PANEL_X;
const INGREDIENTS_PANEL_Y = MAIN_PANEL_Y + MAIN_PANEL_HEIGHT + 10;
const INGREDIENTS_WIDTH = MAIN_PANEL_WIDTH;
const INGREDIENTS_HEIGHT = 330;

const INGREDIENT_WIDTH = 15;
const INGREDIENT_HEIGHT = 20;
const INGREDIENT_NAME_BUFFER = 20;
const INGREDIENT_HORIZONTAL_SEPARATION = INGREDIENT_WIDTH * 4;
const INGREDIENT_VERTICAL_SEPARATION = INGREDIENT_HEIGHT + 15;

const CAULDRON_HIGHLIGHT_BORDER_WIDTH = 3;

const Layout = Object.freeze({
    CONTROL_PANEL_X : CONTROL_PANEL_X,
    CONTROL_PANEL_Y : CONTROL_PANEL_Y,
    CONTROL_PANEL_WIDTH : CONTROL_PANEL_WIDTH,
    CONTROL_PANEL_HEIGHT : CONTROL_PANEL_HEIGHT,

    VISUAL_PANEL_X : VISUAL_PANEL_X,
    VISUAL_PANEL_Y : VISUAL_PANEL_Y,
    VISUAL_PANEL_WIDTH : VISUAL_PANEL_WIDTH,
    VISUAL_PANEL_HEIGHT : VISUAL_PANEL_HEIGHT,

    VISUAL_BPM_X : VISUAL_BPM_X,
    VISUAL_BPM_Y : VISUAL_BPM_Y,

    BPM_WIDGET_X : BPM_WIDGET_X,
    BPM_WIDGET_Y : BPM_WIDGET_Y,
    BPM_WIDGET_WIDTH : BPM_WIDGET_WIDTH,
    BPM_WIDGET_HEIGHT : BPM_WIDGET_HEIGHT,

    OCTAVE_LABEL_X : OCTAVE_LABEL_X,
    OCTAVE_LABEL_Y : OCTAVE_LABEL_Y,

    OCTAVE_WIDGET_X : OCTAVE_WIDGET_X,
    OCTAVE_WIDGET_Y : OCTAVE_WIDGET_Y,
    OCTAVE_WIDGET_WIDTH : OCTAVE_WIDGET_WIDTH,
    OCTAVE_WIDGET_HEIGHT : OCTAVE_WIDGET_HEIGHT,
    OCTAVE_WIDGET_SEGMENTS : OCTAVE_WIDGET_SEGMENTS,

    CHANNEL_LABEL_X : CHANNEL_LABEL_X,
    CHANNEL_LABEL_Y : CHANNEL_LABEL_Y,

    CHANNEL_WIDGET_X : CHANNEL_WIDGET_X,
    CHANNEL_WIDGET_Y : CHANNEL_WIDGET_Y,
    CHANNEL_WIDGET_WIDTH : CHANNEL_WIDGET_WIDTH,
    CHANNEL_WIDGET_HEIGHT : CHANNEL_WIDGET_HEIGHT,
    CHANNEL_WIDGET_SEGMENTS : CHANNEL_WIDGET_SEGMENTS,

    WIDGET_DIVIDER_1_X : WIDGET_DIVIDER_1_X,
    WIDGET_DIVIDER_1_Y : WIDGET_DIVIDER_1_Y,
    WIDGET_DIVIDER_1_WIDTH : WIDGET_DIVIDER_1_WIDTH,

    VALUE_WIDGET_X : VALUE_WIDGET_X,
    VALUE_WIDGET_Y : VALUE_WIDGET_Y,
    VALUE_WIDGET_HEIGHT : VALUE_WIDGET_HEIGHT,
    VALUE_WIDGET_WIDTH : VALUE_WIDGET_WIDTH,

    WIDGET_DIVIDER_2_X : WIDGET_DIVIDER_2_X,
    WIDGET_DIVIDER_2_Y : WIDGET_DIVIDER_2_Y,
    WIDGET_DIVIDER_2_WIDTH : WIDGET_DIVIDER_2_WIDTH,

    MIDI_OUTPUT_X : MIDI_OUTPUT_X,
    MIDI_OUTPUT_Y : MIDI_OUTPUT_Y,

    MAIN_PANEL_X : MAIN_PANEL_X,
    MAIN_PANEL_Y : MAIN_PANEL_Y,
    MAIN_PANEL_WIDTH : MAIN_PANEL_WIDTH,
    MAIN_PANEL_HEIGHT : MAIN_PANEL_HEIGHT,

    INGREDIENTS_PANEL_X : INGREDIENTS_PANEL_X,
    INGREDIENTS_PANEL_Y : INGREDIENTS_PANEL_Y,
    INGREDIENTS_WIDTH : INGREDIENTS_WIDTH,
    INGREDIENTS_HEIGHT : INGREDIENTS_HEIGHT,

    INGREDIENT_WIDTH : INGREDIENT_WIDTH,
    INGREDIENT_HEIGHT : INGREDIENT_HEIGHT,
    INGREDIENT_NAME_BUFFER : INGREDIENT_NAME_BUFFER,
    INGREDIENT_HORIZONTAL_SEPARATION : INGREDIENT_HORIZONTAL_SEPARATION,
    INGREDIENT_VERTICAL_SEPARATION : INGREDIENT_VERTICAL_SEPARATION,

    CAULDRON_HIGHLIGHT_BORDER_WIDTH : CAULDRON_HIGHLIGHT_BORDER_WIDTH,
})

module.exports = Layout;